# Generated by Django 4.1 on 2023-04-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.TextField(max_length=500)),
                ('productQty', models.TextField(max_length=500)),
                ('productPrice', models.TextField(max_length=500)),
                ('productDesc', models.TextField(max_length=500)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='product/image')),
                ('productServing', models.IntegerField()),
                ('isApproved', models.BooleanField(default='False')),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.categories')),
                ('dietType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.diet')),
                ('subcategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.sub_categories')),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('ratingID', models.AutoField(primary_key=True, serialize=False)),
                ('productRating', models.IntegerField(default=5)),
                ('productReview', models.TextField(max_length=500)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.product')),
            ],
        ),
    ]
