# Generated by Django 4.1 on 2023-04-19 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0006_delete_admin_registration'),
        ('administrator', '0004_diet'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.TextField(max_length=500)),
                ('productQty', models.TextField(max_length=500)),
                ('productPrice', models.TextField(max_length=500)),
                ('productDesc', models.TextField(max_length=500)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='product/image')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.user')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.categories')),
                ('dietId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.diet')),
                ('subcategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.sub_categories')),
            ],
        ),
    ]
