# Generated by Django 4.1 on 2023-04-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryId',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='dietId',
            new_name='dietType',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategoryId',
            new_name='subcategoryName',
        ),
    ]
