# Generated by Django 4.1 on 2023-04-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_rename_categoryid_product_categoryname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='UserId',
        ),
    ]
