# Generated by Django 4.1 on 2023-05-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_alter_product_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.TextField(max_length=500),
        ),
    ]
