# Generated by Django 4.1 on 2023-05-02 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_alter_product_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productQty',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
