# Generated by Django 4.1 on 2023-05-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_alter_product_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productQty',
            field=models.FloatField(),
        ),
    ]
