# Generated by Django 4.1 on 2023-04-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_product_productrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productRating',
        ),
    ]
