# Generated by Django 4.1 on 2023-04-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('password', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='seller_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('contact', models.TextField(max_length=10)),
                ('companyname', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='auth_app/static/user_profile')),
                ('password', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('contact', models.TextField(max_length=10)),
                ('address', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='auth_app/static/user_profile')),
                ('password', models.TextField(max_length=50)),
            ],
        ),
    ]
