# Generated by Django 4.1 on 2023-05-02 08:19
# Generated by Django 4.1 on 2023-05-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='Gujarat', max_length=30),
        ),
        migrations.AddField(
            model_name='merchant',
            name='shopCity',
            field=models.CharField(default='Ahmedabad', max_length=30),
        ),
        migrations.AddField(
            model_name='merchant',
            name='shopState',
            field=models.CharField(default='Gujarat', max_length=30),
        ),
    ]
