# Generated by Django 4.1 on 2023-04-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('userAddress', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='merchant',
            fields=[
                ('MerchId', models.AutoField(primary_key=True, serialize=False)),
                ('shopName', models.TextField(max_length=50)),
                ('shopAddr', models.TextField(max_length=500)),
                ('shopPhone', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('contact', models.TextField(max_length=10)),
                ('address', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='auth_app/static/user_profile')),
                ('password', models.TextField(max_length=50)),
                ('user_type', models.IntegerField()),
                ('isAdmin', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='admin_registration',
        ),
        migrations.DeleteModel(
            name='seller_registration',
        ),
        migrations.DeleteModel(
            name='user_registration',
        ),
        migrations.AddField(
            model_name='merchant',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.user'),
        ),
    ]
