# Generated by Django 4.1 on 2023-03-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_user_registration_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auth_app/static/user_profile'),
        ),
    ]
