# Generated by Django 4.1 on 2023-04-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_admin_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_registration',
        ),
    ]
