# Generated by Django 4.1 on 2023-03-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_alter_user_registration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='contact',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auth_app/static/user_profile'),
        ),
    ]
