# Generated by Django 4.1 on 2023-03-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_alter_user_registration_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='contact',
            field=models.TextField(max_length=10),
        ),
    ]
