# Generated by Django 4.1 on 2023-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_alter_user_registration_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='email',
            field=models.EmailField(blank=True, max_length=50, unique=True),
        ),
    ]
