# Generated by Django 4.1 on 2023-03-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_alter_user_registration_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('contact', models.TextField(max_length=10)),
                ('companyname', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='auth_app/static/user_profile')),
                ('password', models.TextField(max_length=50)),
            ],
        ),
    ]
