# Generated by Django 4.1 on 2023-04-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.TextField(blank=True, max_length=50)),
                ('categoryImage', models.ImageField(blank=True, null=True, upload_to='administrator/image')),
            ],
        ),
    ]
