# Generated by Django 4.1 on 2023-04-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categoryName',
            field=models.TextField(blank=True, max_length=50, unique=True),
        ),
    ]
