# Generated by Django 4.1 on 2023-04-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_categories',
            name='categoryName',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Sub_Categories',
        ),
    ]
