# Generated by Django 4.1 on 2023-04-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('dietId', models.AutoField(primary_key=True, serialize=False)),
                ('dietType', models.TextField(blank=True, max_length=50, unique=True)),
                ('dietDisc', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
