# Generated by Django 4.1 on 2023-04-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='UserId',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
