# Generated by Django 4.1 on 2023-04-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_cartitems_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='quantity',
        ),
    ]
