# Generated by Django 4.1 on 2023-05-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_bill_billitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitems',
            name='productQty',
        ),
    ]
