# Generated by Django 4.1 on 2023-05-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_billitems_productqty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('number', models.IntegerField(max_length=10)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
