# Generated by Django 4.1 on 2023-05-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_alter_product_productname'),
        ('user', '0006_remove_billitems_productqty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=255)),
                ('recipe_instructions', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_quantity', models.FloatField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.recipe')),
            ],
        ),
    ]
