# Generated by Django 4.1 on 2023-05-02 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='dateOfGeneration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
