# Generated by Django 4.1 on 2023-05-02 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_alter_product_productname'),
        ('user', '0010_bill_dateofgeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitems',
            name='productId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='merchant.product'),
            preserve_default=False,
        ),
    ]
