# Generated by Django 4.1 on 2023-05-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_billitems_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitems',
            name='productQty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
