# Generated by Django 4.1 on 2023-05-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_recipe_ingredient'),
        ('user', '0012_billitems_productqty'),
    ]

    operations = [
    ]
