# Generated by Django 4.1 on 2023-05-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_merge_20230503_0127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
